name: pdtk # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: pdtk is a toolkit for writing with Pandoc # 79 char long summary
description: |
  pdtk is a tool kit for writing. The main focus is on static site
  generation using Pandoc.  The metaphor behind the tool kit is a
  deconstructed content management system. It is easily scripted from
  your favorite POSIX shell or Makefile. It provides a number of functions
  including a Pandoc preprocessor called prep, a blogging tool called
  blogit as well as an RSS generator. In this way you should be able to
  have many of the website features you'd expect from a dynamic content
  management system like Wordpress without the need to run one.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict #devmode # use 'strict' once you have the right plugs and slots

apps:
  pdtk:
    command: bin/pdtk
    plugs:
      - home
      - desktop
      - removable-media
      - network

parts:
#  pandoc:
#    plugin: conda
#    conda-packages:
#      - -c
#      - conda-forge
#      - pandoc
  pdtk:
    plugin: go
    go-channel: stable
    build-environment:
        - "CGO_ENABLED" : "1"
    source-type: git
    source: https://github.com/rsdoiel/pdtk
    stage-packages:
      - pandoc
