name: pttk # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.0.11' # just for humans, typically '1.2+git' or '1.3.2'
summary: pttk is a plain text toolkit for writing and content organization
description: |
    pttk implements a deconstructed content management system suitable for
    working with plain text. It intended as a compliment to Pandoc focusing
    on collections of documents and structed text.  Currently pttk provides
    tools to layout blog directories, generate Gophermap files for Gopher
    distribution.  The ideas is to provide the tooling that will allow
    publication and distribution both on the world wide web as well as
    the "small internet".

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict #devmode # use 'strict' once you have the right plugs and slots

apps:
  pttk:
    command: bin/pttk
    plugs:
      - home
      - desktop
      - removable-media
      - network

parts:
  pttk:
    plugin: go
    go-channel: stable
    build-environment:
      - "CGO_ENABLED" : "1"
    source-type: git
    source: https://github.com/rsdoiel/pttk
